x-google-marketplace:
  schemaVersion: v2

application_api_version: v1beta1
properties:
name:
  type: string
  x-google-marketplace:
   type: NAME
namespace:
  type: string
  x-google-marketplace:
   type: NAMESPACE
imagerelease:
  type: string
  default: gcr.io/digitalai-public/release/xl-release:24.2
  x-google-marketplace:
   type: IMAGE
  
required:
- name
- namespace
