x-google-marketplace:
  schemaVersion: v2

  application_api_version: v1beta1
  publishedVersion: '24.2'
  publishedVersionMetadata:
    releaseNote: >-
      Security fix release.
    releaseTypes:
    - Security
    recommended: true
  images:
    '':  # Primary image has no name.
      properties:
        imageRepo:
          type: REPO_WITH_REGISTRY
        imageTag:
          type: TAG
properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE  
  required:
  - name
  - namespace

